#!/bin/sh

TOP=${1:-/mnt}

grep '^[0-9a-f]\{32\}  ./' $TOP/VERSION | grep -v rootfs.ext2 | grep -v fpga.d >/tmp/release.md5

(
	cd $TOP
	md5sum ./RELEASENOTES ./bin/* 
	md5sum ./boot.d/* ./dtb.d/* ./z7io/*
	md5sum ./ko/package*
	md5sum ./packages/* 
	md5sum ./packages.opt/* 
	md5sum ./uImage ./uramdisk.image.gz 
	[ -e ./rootfs.ext2.gz ] && md5sum ./rootfs.ext2.gz
) | sort -k 2 -f -d | grep -v rootfs.ext2 >/tmp/current.md5

echo RELEASE : /tmp/release.md5
echo CURRENT : /tmp/current.md5


if [ -e /etc/acq400_version ]; then
	echo "Base file system /etc/acq400_version:"
	cat /etc/acq400_version
	diff -uU 0 /etc/acq400_version /mnt2/etc/acq400_version  >/dev/null
	OK=$?
	if [ $OK -ne 0 ]; then
		echo "WARNING: rootfs build is different:"
		cat /mnt2/etc/acq400_version
	fi
fi

	
diff -uU 0 /tmp/release.md5 /tmp/current.md5 | grep -v @@
diff -uU 0 /tmp/release.md5 /tmp/current.md5 >/dev/null
OK=$?


if [ "x$TOP" = "x/mnt" ]; then
	VERHEAD=$(head -n1 /mnt/VERSION)
	if [ $OK -eq 0 ]; then
		echo $VERHEAD
		echo "Clean Release Installed"
		RC=0
	else
		echo "Warning, patching detected"
		RC=1
	fi
	ls /mnt/ko/*fpga*
	if [ $(ls /mnt/ko/*fpga* | wc -l) -eq 1 ]; then
		ESW_DC=$(echo $VERHEAD | sed -e 's/-/ /g' | awk '{ print $4 }')
		GW_DC=$(ls /mnt/ko/*fpga* | tr .- ' ' | awk '{ print $3 }')
		if [ "$ESW_DC" = "$GW_DC" ]; then
			echo "ESW and GW DATECODES $ESW_DC MATCH: GOOD"
			exit $RC
		else
			echo "Warning: ESW DATECODE $ESW_DC does not match GW $GW_DC"
			exit 1
		fi
	else
		echo "ERROR: multiple FPGA archives NOT RECOMMENDED"
		exit 1
	fi
else
	if [ $OK -eq 0 ]; then
		echo "VALID RELEASE"
		exit 0
	else
		if [ -e /mnt/ko/fpga-$RELCORE.img ]; then
			(cd /mnt; md5sum ./ko/fpga-$RELCORE.img >>/tmp/current.md5)
			sort -t\  -k2 /tmp/current.md5 >/tmp/current.md5.2
			sort -t\  -k2 /tmp/release.md5 >/tmp/release.md5.2
			diff -uU 0 /tmp/release.md5.2 /tmp/current.md5.2 >/dev/null
			if [ $? -eq 0 ]; then
				echo "WITH /mnt/ko/fpga-$RELCORE.img included, RELEASES MATCH"
				exit 0
			fi
		fi		
		echo "ERROR release invalid"
		exit 1
	fi
fi

