#!/bin/sh

TOP=${1:-/mnt}

grep '^[0-9a-f]\{32\}  ./' $TOP/VERSION | grep -v rootfs.ext2 | grep -v fpga.d >/tmp/release.md5

(
	cd $TOP
	md5sum ./RELEASENOTES ./bin/* 
	md5sum ./boot.d/* ./dtb.d/* ./fpga.d/* 
	md5sum ./ko/*
	md5sum ./packages/* 
	md5sum ./packages.opt/* 
	md5sum ./uImage ./uramdisk.image.gz 
	[ -e ./rootfs.ext2.gz ] && md5sum ./rootfs.ext2.gz
) | sort -k 2 -f -d | grep -v rootfs.ext2 >/tmp/current.md5

echo RELEASE : /tmp/release.md5
echo CURRENT : /tmp/current.md5


diff -uU 0 /tmp/release.md5 /tmp/current.md5 | grep -v @@
diff -uU 0 /tmp/release.md5 /tmp/current.md5 >/dev/null
OK=$?

if [ "x$TOP" = "x/mnt" ]; then
	if [ $OK -eq 0 ]; then
		head -n1 /mnt/VERSION
		echo Clean Release Installed
		exit 0
	else
		echo Warning, patching detected
		exit 1
	fi
else
	if [ $OK -eq 0 ]; then
		echo VALID RELEASE
		exit 0
	else
		echo ERROR release invalid
		exit 1
	fi
fi


	
